name: Deploy Traium By Traium CI

on:
  push:
    branches: [ "ver/1.21.8" ]
    paths-ignore:
      - README.md
      - LICENSE.md
      - .gitignore
      - licenses/**/*
      - public/**/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: Checkout Git
        uses: actions/checkout@v5

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Run Deploy Bash
        run: sh scripts/build_1.21.8.sh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.commit_id }}
          name: Traium ${{ env.mcversion }} - ${{ env.commit_id }}
          body: |
            ### 📦 Version: `${{ env.mcversion }}` | Commit: [${{ env.commit_id }}](https://github.com/CoderFrish/commit/${{ env.commit_id }})
            ![download](https://img.shields.io/github/downloads/CoderFrish/Traium/${{ env.commit_id }}/total?style=for-the-badge)
              
            > This release is automatically built by GitHub Actions.
              
            #### 📜 Latest Commit Message:
            ${{ env.commit_msg }}
              
            #### 📊 Build Information:
            - **Build Status**: ✅ Success
            - **Build Date**: ${{ env.build_date }}
          artifacts: traium-server/build/libs/Traium-${{ env.version }}.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
